config/routes.rb
Rails.application.routes.draw do
  devise_for :clientes
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :pedidos, only: [:index, :create, :destroy] do
    get :checkout, on: :collection
  end
  resources :produtos, only: [:index, :show] do
    get 'categoria/:nome', action: :por_categoria, on: :collection, as: 'categoria'
  end

  root 'produtos#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  has_many :produtos
  validates :nome, presence: true, uniqueness: true

  def to_s
    nome
  end
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable,
         :trackable, authentication_keys: [:username]

  has_many :produtos, through: :pedidos
  has_many :pedidos

  validates_presence_of :name, :username

  validates_presence_of      :password, on: :create
  validates_confirmation_of  :password, on: :create
  validates_length_of        :password, maximum: 25, minimum: 4, on: :create


  def checkout
    pedidos.pendente.update_all(status: Pedido.statuses[:pago])
  end

  def to_s
    name
  end
end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
  before_save   :verificar_estoque
  after_destroy :devolver_estoque
  enum status: [ :pendente, :pago ]

  belongs_to :produto
  belongs_to :cliente

  validates_presence_of :produto_id, :cliente_id
  validates_associated :produto, :cliente


  def self.valor_total(pedidos)
    total = 0
    pedidos.each do |pedido|
      total += pedido.produto.preco
    end
    total
  end

  private
  def verificar_estoque
    if produto.quantidade > 0
      produto.quantidade -= 1
      produto.save
    else
      errors.add(:produto, 'Produto fora de estoque')
      false
    end
  end

  def devolver_estoque
    produto.quantidade += 1
    produto.save
  end
end

app/models/produto.rb
class Produto < ActiveRecord::Base
  has_many :pedidos
  has_many :clientes, through: :pedidos
  belongs_to :categoria

  validates_uniqueness_of :nome
  validates_presence_of :nome, :quantidade, :preco, :categoria_id
  validates_associated :categoria

  def to_s
    nome
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pedidos_controller.rb
#encoding: UTF-8

class PedidosController < InheritedResources::Base
  before_action :verificar_cliente

  def index
    @pedidos = Pedido.includes(:produto).where(cliente: current_cliente).pendente
    @total   = Pedido.valor_total @pedidos
  end

  def create
    pedido = Pedido.new(pedido_params)
    if pedido.save
      redirect_to root_path, notice: 'Pedido foi adicinado a sua lista'
    else
      redirect_to root_path, alert: pedido.errors.full_messages.join
    end
  end

  def destroy
    pedido = Pedido.includes(:produto).find(params[:id])
    redirect_validator(pedidos_path, "Pedido foi removido da sua lista (#{pedido.produto.nome})", 'Erro ao remover o pedido') { pedido.destroy }
  end

  def checkout
    redirect_validator(root_path, 'Todos os pedidos foram pagos', 'Erro ao pagar os pedidos') { current_cliente.checkout }
  end

  private
  def redirect_validator(path, message_accept, message_error)
    if yield
      redirect_to path, notice: message_accept
    else
      redirect_to path, alert: message_error
    end
  end

  def verificar_cliente
    unless cliente_signed_in?
      redirect_to new_cliente_session_path, alert: 'Você precisa de uma conta antes de comprar algo'
    end
  end

  def pedido_params
    params.require(:pedido).permit(:cliente_id, :produto_id)
  end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController

  def index
    @produtos = Produto.all
  end

  def show
    @produto = Produto.find(params[:id])
  end

  def por_categoria
    @categoria = Categoria.includes(:produtos).find_by_nome params[:nome]
    @produtos  = @categoria.produtos
    render 'index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def categorias
    Categoria.all
  end
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/layouts/_categorias.html.erb
<% if categorias == selected %>
    <% id = 'categoria-selected' %>
<% else %>
    <% id = categorias.nome %>
<% end %>

<%= link_to(categorias.nome, categoria_produtos_path(categorias.nome), class: 'list-group-item', id: id) %>

app/views/layouts/_cliente.html.erb
<% if cliente_signed_in? %>
    <li>
      <a class="login-header no-select"><%= "Olá #{current_cliente.name}" %></a>
    </li>
    <li>
      <%= link_to 'Pedidos', pedidos_path, class: 'login-header' %>
    </li>
    <li>
      <%= link_to 'Sair', destroy_session_path(:cliente), method: :delete, class: 'login-header' %>
    </li>
<% else %>
    <li>
      <%= link_to 'Logar', new_cliente_session_path, class: 'login-header' %>
    </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PalomLoja</title>
  <%= stylesheet_link_tag 'application', params[:controller], :media => 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application',  params[:controller], 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- Navigation Top -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'PalomLoja', root_path, class: 'navbar-brand' %>

        <ul class="nav navbar-nav" id="navbar-head-login">
          <%= render 'layouts/cliente' %>
        </ul>
      </div>

    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    </div>
  </div>
  <!-- /.container -->
</nav>

<%= bootstrap_flash %>

<!-- Page Content -->
<div class="container">

  <div class="row">

    <% unless params[:controller].start_with? 'devise' %>
        <div class="col-md-3">
          <div class="list-group">
            <%= link_to('Todas', root_path, class: @categoria ? 'list-group-item' : 'list-group-item categoria-select') %>
            <%= render partial: 'layouts/categorias', collection: categorias, locals: {selected: @categoria} %>
          </div>
        </div>
    <% end %>
    <%= yield %>
  </div>
</div>
<!-- /.container -->

</body>
</html>

app/views/pedidos/_pedido.html.erb
<div class="col-sm-4 col-lg-4 col-md-4">
  <div class="thumbnail">
    <img src="http://placehold.it/320x150" alt="">

    <div class="caption">
      <h4 class="pull-right"><%= number_to_currency(pedido.produto.preco) %></h4>
      <h4><%= link_to pedido.produto.nome, produto_path(pedido.produto) %></h4>
      <h5><%= link_to('Deletar pedido', pedido_path(pedido), method: :delete, class: 'delete') %></h5>
    </div>
  </div>
</div>

app/views/pedidos/index.html.erb
<div class="col-md-9">
  <div class="row">
    <% if @pedidos.any? %>
        <%= render partial: 'pedido', collection: @pedidos %>
        <div class="col-md-9">
          <div class="row">
            <h3> Total: <%= @total %></h3>
            <%= link_to 'Checkout', checkout_pedidos_path, class: 'btn btn-success btn-lg' %>
          </div>
    <% else %>
        <h3>Não existe nenhum pedido na sua lista</h3>
    <% end %>
        </div>
  </div>
</div>

app/views/produtos/_produto.html.erb
<div class="col-sm-4 col-lg-4 col-md-4">
  <div class="thumbnail">
    <img src="http://placehold.it/320x150" alt="">

    <div class="caption">
      <h4 class="pull-right"><%= number_to_currency(produto.preco) %></h4>
      <h4><%= link_to produto.nome, produto_path(produto) %></h4>
    </div>
  </div>
</div>

app/views/produtos/index.html.erb
<div class="col-md-9">

  <!--<div class="row carousel-holder">-->

    <!--<div class="col-md-12">-->
      <!--<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">-->
        <!--<ol class="carousel-indicators">-->
          <!--<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>-->
          <!--<li data-target="#carousel-example-generic" data-slide-to="1"></li>-->
          <!--<li data-target="#carousel-example-generic" data-slide-to="2"></li>-->
        <!--</ol>-->
        <!--<div class="carousel-inner">-->
          <!--<div class="item active">-->
            <!--<img class="slide-image" src="http://placehold.it/800x300" alt="">-->
          <!--</div>-->
          <!--<div class="item">-->
            <!--<img class="slide-image" src="http://placehold.it/800x300" alt="">-->
          <!--</div>-->
          <!--<div class="item">-->
            <!--<img class="slide-image" src="http://placehold.it/800x300" alt="">-->
          <!--</div>-->
        <!--</div>-->
        <!--<a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">-->
        <!--</a>-->
        <!--<a class="right carousel-control" href="#carousel-example-generic" data-slide="next">-->
        <!--</a>-->
      <!--</div>-->
    <!--</div>-->

  <!--</div>-->

  <div class="row">
    <% if @produtos.any? %>
        <%= render partial: 'produto', collection: @produtos %>
    <% else %>
        <h3>Não existe nenhum produto nessa categoria</h3>
    <% end %>
  </div>
</div>

app/views/produtos/show.html.erb
<div class="col-md-9">
  <div class="col-md-6">
    <img src="http://placehold.it/400x300">
  </div>
  <div class="col-md-5">
    <h2><%= @produto.nome %></h2>
    <h3>Quantidade: <%= @produto.quantidade %></h3>
    <h4><%= number_to_currency(@produto.preco) %></h4>
    <%= link_to 'Comprar', pedidos_path(pedido: { cliente_id: current_cliente, produto_id: @produto }), method: :post, class: 'btn btn-success btn-lg' %>
  </div>
</div>